<a href="https://colab.research.google.com/github/SuganthiEvangeline/Fundamental/blob/main/Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#How do you create a 1D NumPy array containing integers from 10 to 20?

import numpy as np
arr = np.arange(10, 21)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#What is the difference between a NumPy array’s .ndim and .shape attributes?
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)   # Output: 2 (2D array)
print(arr.shape)  # Output: (2, 3) (2 rows, 3 columns)


2
(2, 3)


In [ ]:
#Code to calculate the sum of all elements in a NumPy array
arr = np.array([1, 2, 3, 4])
total_sum = np.sum(arr)
print(total_sum)


10


In [ ]:
#Extract the first three elements from the array
arr = np.array([5, 10, 15, 20])
first_three = arr[:3]
print(first_three)


[ 5 10 15]


In [ ]:
#Default data type of NumPy arrays and setting to float
arr = np.array([1, 2, 3], dtype=float)
print(arr.dtype)  # Output: float64


float64


In [ ]:
#Add two NumPy arrays element-wise and explain broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)  # Output: [5, 7, 9]


[5 7 9]


In [ ]:
#Calculate mean, median, and standard deviation of a NumPy array
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
print(mean, median, std_dev)


3.0 3.0 1.4142135623730951


In [ ]:
#Reshape a 1D array of size 12 into 2D array with 3 rows and 4 columns

arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#Filter elements greater than 5

arr = np.array([2, 5, 8, 1, 9])
filtered = arr[arr > 5]
print(filtered)  # Output: [8, 9]

[8 9]


In [ ]:
#Compute the dot product of two 2D NumPy arrays

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr1, arr2)
print(dot_product)

[[19 22]
 [43 50]]


In [ ]:
#Explain broadcasting in NumPy with example
#Concept: NumPy automatically expands smaller arrays along their dimensions to perform element-wise operations without explicit replication.

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
result = arr1 + arr2  # Broadcasting: arr1 shape (3,) aligns with arr2 shape (3, 1)
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
#Memory efficiency of NumPy vs Python lists

import numpy as np
import sys

list_data = list(range(1000))
array_data = np.arange(1000)

print(sys.getsizeof(list_data))  # Size of Python list
print(array_data.nbytes)         # Size of NumPy array

8056
8000


In [ ]:
#Extract even numbers from a 2D NumPy array

arr = np.array([[1, 2, 3], [4, 5, 6]])
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[2 4 6]


In [ ]:
#Generate a 5x5 matrix with random numbers and compute determinant

from numpy.random import randn
from numpy.linalg import det

matrix = randn(5, 5)  # Standard normal distribution
determinant = det(matrix)
print(matrix)
print(determinant)

[[ 0.92176967 -0.86265381 -2.5440935  -2.2882831  -0.91470794]
 [-1.10641601 -0.41374571 -0.31456897 -0.31670948 -1.69696851]
 [-0.26017627 -0.4471715   2.30026826  0.02106006  1.22327788]
 [ 2.22911899  1.23667468  0.83316789 -0.08976738  0.85633811]
 [-0.29819396 -0.61347375  0.19148677  1.82761177 -0.62499517]]
-32.45716866422376


In [ ]:
#Create a Pandas DataFrame from a dictionary of lists

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [ ]:
import pandas as pd
#Read a CSV file and display the first 5 rows
df = pd.read_csv("insurance.csv")
print(df.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520


In [ ]:
#Select a single column named age from a DataFrame
age_column = df['age']
print(age_column)

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64


In [ ]:
#Display a summary of the DataFrame

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [ ]:
#Filter rows where the sales column has values greater than 100

filtered_df = df[df['bmi'] < 100]
print(filtered_df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [ ]:
#Replace all NaN values with the median value of the respective column

df = df.fillna(df.median(numeric_only=True))
print(df)

In [ ]:
#Merge two DataFrames on a common column using an inner join

merged_df = pd.merge(df1, df2, on='id', how='inner')
print(merged_df)

NameError: name 'df1' is not defined

In [ ]:
#Sort a DataFrame by a column in descending order

sorted_df = df.sort_values(by='price', ascending=False)
print(sorted_df)

In [ ]:
 #Create a MultiIndex DataFrame

data = {
    'Population': [100, 200, 150],
    'GDP': [5000, 10000, 7500]
}
index = pd.MultiIndex.from_tuples([('USA', 2020), ('USA', 2021), ('Canada', 2020)], names=['Country', 'Year'])
multi_index_df = pd.DataFrame(data, index=index)
print(multi_index_df)

              Population    GDP
Country Year                   
USA     2020         100   5000
        2021         200  10000
Canada  2020         150   7500


In [ ]:
#Create a pivot table summarizing average sales for each region and product

pivot_table = df.pivot_table(values='sales', index='region', columns='product', aggfunc='mean')
print(pivot_table)

KeyError: 'sales'

In [ ]:
#Calculate the rolling mean of a column over a window size of 3

df['rolling_mean'] = df['temperature'].rolling(window=3).mean()
print(df)

In [ ]:
#Apply a custom function to normalize a column

def normalize(column):
    return (column - column.min()) / (column.max() - column.min())

df['normalized_score'] = normalize(df['score'])
print(df)

In [ ]:
#Extract month and year from a datetime column

df['month'] = pd.to_datetime(df['date']).dt.month
df['year'] = pd.to_datetime(df['date']).dt.year
print(df)

KeyError: 'date'